In [2]:
import layer_naive
apple = 100
num_apple = 2
tax = 1.1

# layer
mul_apple_layer = layer_naive.MulLayer()
mul_tax_layer = layer_naive.MulLayer()

# forward
price_apple = mul_apple_layer.forward(apple, num_apple)
price = mul_tax_layer.forward(price_apple, tax)
print(price)

# backward
dprice = 1
dapple_price, dtax = mul_tax_layer.backward(dprice)
dapple, dapple_num = mul_apple_layer.backward(dapple_price)
print(dtax, dapple_price, dapple_num, dapple)

220.00000000000003
200 1.1 110.00000000000001 2.2


In [7]:
import layer_naive
import importlib
importlib.reload(layer_naive)

apple = 100
num_apple = 2
orange = 150
num_orange = 3
tax = 1.1

# layer
mul_apple_layer = layer_naive.MulLayer()
mul_orange_layer = layer_naive.MulLayer()
add_layer = layer_naive.AddLayer()
mul_tax_layer = layer_naive.MulLayer()

# forward 
price_apple = mul_apple_layer.forward(apple, num_apple)
price_orange = mul_orange_layer.forward(orange, num_orange)
price_sum = add_layer.forward(price_apple, price_orange)
price = mul_tax_layer.forward(price_sum, tax)
print(price)

#backward
dprice = 1
dprice_sum, dtax = mul_tax_layer.backward(dprice)
dprice_apple, dprice_orange = add_layer.backward(dprice_sum)
dapple, dnum_apple = mul_apple_layer.backward(dprice_apple)
dorange, dnum_orange = mul_orange_layer.backward(dprice_orange)
print(dprice_apple, dprice_orange, dapple, dnum_apple, dorange, dnum_orange)

715.0000000000001
1.1 1.1 2.2 110.00000000000001 3.3000000000000003 165.0


In [10]:
a = np.arange(10)
np.where(a>5, a, 0)

array([0, 0, 0, 0, 0, 0, 6, 7, 8, 9])

In [ ]:
import os
import sys
sys.path.append(os.pardir)
from dataset.mnist import load_mnist
from twolayers import TwoLayerNet

(x_train, t_train), (x_test, t_test) =\
    load_mnist(normalize=True, one_hot_label=True)

network = TwoLayerNet(x_train.shape[1], 50, t_train.shape[1])

iters_num = 10000
train_size = x_train.shape[0]
batch_size = 100
learning_rate = 0.1
train_loss_list = []
train_acc_list = []
test_acc_list = []

n_epoch = max(int(train_size / batch_size), 1)

for i in range(iters_num):
    batch_mask = np.random.choice(train_size, batch_size)
    x_batch = x_train[batch_mask]
    t_batch = t_train[batch_mask]

    grad = network.gradient(x_batch, t_batch)
    print(grad)

    for key in ('W1', 'b1', 'W2', 'b2'):
        network.params[key] -= learning_rate * grad[key]

    loss = network.loss(x_batch, t_batch)
    train_loss_list.append(loss)

    if i % n_epoch == 0:
        train_acc = network.accuracy(x_train, t_train)
        test_acc = network.accuracy(x_test, t_test)
        train_acc_list.append(train_acc)
        test_acc_list.append(test_acc)
        print(train_acc, test_acc)


{'b1': array([  3.08596284e-04,  -5.17374362e-04,  -5.04584293e-05,
         1.91109009e-04,   1.56709394e-03,  -8.25158430e-04,
         7.73571194e-04,  -1.67564225e-04,   1.29862425e-03,
         2.86598357e-04,   1.23853683e-04,  -8.78942178e-04,
        -8.55584205e-04,   1.27542204e-03,  -1.00743623e-03,
        -1.46183075e-03,   3.93264836e-04,  -6.42114738e-04,
         4.18012491e-04,  -6.44419570e-04,   1.13473522e-03,
        -1.73252472e-03,   1.25146446e-03,   2.46208033e-03,
        -3.09951410e-04,   0.00000000e+00,   8.33101738e-05,
        -2.71545252e-04,   9.43641282e-04,   2.07579331e-03,
        -2.29296975e-04,   3.21084748e-06,  -4.57216937e-04,
        -3.08056763e-04,   1.06864176e-04,   5.89107117e-04,
        -1.61834589e-04,   3.00958315e-04,   5.64313566e-04,
         1.18676539e-04,   1.87240294e-04,  -5.21445159e-04,
         2.06785656e-04,  -2.79995017e-04,  -1.31443058e-04,
        -6.13119538e-04,  -3.79466839e-04,   6.85828932e-04,
        -4.788914

In [15]:
a = np.arange(6).reshape(3,2)
np.max(a, axis=1).reshape(3, 1)

array([[1],
       [3],
       [5]])

In [17]:
a = np.arange(6).reshape(3,2)
a/np.sum(a, axis=1)

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [22]:
print(a[:, (0, 0, 0)])
print(a)

[[0 0 0]
 [2 2 2]
 [4 4 4]]
[[0 1]
 [2 3]
 [4 5]]
